application: foretribebigquery
version: 1
runtime: python27
api_version: 1
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 5  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 50

threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /css/*
  static_dir: css

- url: /js
  static_dir: js

- url: /bower_components
  static_dir: bower_components

- url: /views
  static_dir: views

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: pycrypto
  version: "latest"

- name: jinja2
  version: "latest"

- name: ssl
  version: "latest"
